<?php

namespace SeinopSys\OAuth2\Client\Provider;

use League\OAuth2\Client\Provider\AbstractProvider;
use League\OAuth2\Client\Provider\Exception\IdentityProviderException;
use League\OAuth2\Client\Token\AccessToken;
use League\OAuth2\Client\Tool\BearerAuthorizationTrait;
use Psr\Http\Message\ResponseInterface;

class DeviantArtProvider extends AbstractProvider
{
    use BearerAuthorizationTrait;

    /**
     * PKCE method to use, or null to not use PKCE. Set via the 'pkceMethod' constructor option, e.g.
     * `'pkceMethod' => DeviantArtProvider::PKCE_METHOD_S256`. DeviantArt requires PKCE for newly
     * registered applications ("The code_challenge parameter is required.").
     *
     * When enabled, the code verifier generated by getAuthorizationUrl() must be kept (e.g. in the
     * session) via getPkceCode() and restored with setPkceCode() before exchanging the authorization
     * code for an access token.
     *
     * @var string|null
     */
    protected $pkceMethod = null;

    protected function getPkceMethod()
    {
        return $this->pkceMethod;
    }

    public function getBaseAuthorizationUrl()
    {
        return 'https://www.deviantart.com/oauth2/authorize';
    }

    public function getBaseAccessTokenUrl(array $params)
    {
        return 'https://www.deviantart.com/oauth2/token';
    }

    public function getResourceOwnerDetailsUrl(AccessToken $token)
    {
        return 'https://www.deviantart.com/api/v1/oauth2/user/whoami';
    }

    protected function getDefaultScopes()
    {
        return ['user'];
    }

    protected function checkResponse(ResponseInterface $response, $data)
    {
        if (isset($data['error'])) {
            throw new IdentityProviderException(
                $data['error'] ?: $response->getReasonPhrase(),
                $response->getStatusCode(),
                $response->getBody()
            );
        }
    }

    protected function createResourceOwner(array $response, AccessToken $token)
    {
        return new DeviantArtResourceOwner($response);
    }

    protected function getScopeSeparator()
    {
        return ' ';
    }

    /**
     * @inheritdoc
     * @throws IdentityProviderException
     */
    protected function parseResponse(ResponseInterface $response)
    {
        $statusCode = $response->getStatusCode();
        if ($statusCode > 500) {
            throw new IdentityProviderException(
                'The OAuth server returned an unexpected response',
                $statusCode,
                $response->getBody()
            );
        }

        return parent::parseResponse($response);
    }
}
